### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by jasursadikov** [FelipeFTN/Emoji-Copy#62] opened 2024-08-17 09:13 UTC
## Bug Report

**Current Behavior**
Whenever I do input into a search bar I do not find the desired emoji

**Expected behavior/code**
Whenever I type the name of emoji, I should get the emoji.

**Environment**

Version 23
ArchLinux

![image](https://github.com/user-attachments/assets/cc945bb1-9b33-4936-a902-8a7cd8ac0bff)
![image](https://github.com/user-attachments/assets/3901754c-2558-4593-b4ab-a3508a25eccc)
![image](https://github.com/user-attachments/assets/cf17fbcf-99a5-4c43-a120-8c6f221f0168)

But it does seem to work in some cases:
![image](https://github.com/user-attachments/assets/ae81da99-40f7-4bf8-a9c8-07d99d538146)

**Comment by FelipeFTN** [comment] 2024-08-17 14:15
**Hello, @jasursadikov! Thanks for reporting this issue! :rocket:** 

Well, that's pretty strange. Can you give me some steps to try to reproduce this behavior here?
I just tried enabling and disabling the extension many times, restarting the session and opening and closing the panel, nothing seems to work in order to achieve this bug :confused: 

But for now, I can recommend you to reinstall the extension by cloning this repo, and running: `make install`. This might have some effect, I hope haha :pray: 

If it still doesn't work, please, try to run it in debug mode by running `make debug` in the repo's directory (If you get any error, try restarting the session and entering again in Gnome Xorg instead of Wayland please).

**Please, let me know if these steps help you!**

**Comment by jasursadikov** [comment] 2024-08-17 16:25
I have no idea, I reinstalled the extensions and the issue persists.

I do run Waylands instead of X11.
![image](https://github.com/user-attachments/assets/d5c462d0-82ab-4916-ba2d-5fc114052fe0)

I am not really sure how to do the `make debug` what am I doing wrong?
![image](https://github.com/user-attachments/assets/09a731b2-517a-4e55-8401-fc8a2b004256)

**Comment by FelipeFTN** [comment] 2024-08-17 19:35
Hello, again!

Yes, you have to clone the repository Emoji-Copy into you computer.
In your case, the `make debug` didn't work because the `emoji-copy@felipeftn/` contains only the "compiled/builded" files for the Extension to work properly. So it doesn't have the `Makefile`.

In order to install the files directly from source, you will need to clone the repository, and inside the cloned folder, you run `make debug` :smiley:

Here are the steps:
1. `git clone https://github.com/FelipeFTN/Emoji-Copy`
2.  `cd Emoji-Copy`
3. `make && make install`
4. (test the extension to see if the issue got solved)
5. (if not, then) make debug

Please send me any questions you may have! If nothing goes wrong, a new gnome session will open, and your terminal will start logging all the stuff!
You should try to reproduce the behavior inside the gnome session window that will open, and see the related logs in the terminal - after this, please send me some screenshots of the logs? :pray:

**Comment by jasursadikov** [comment] 2024-08-20 07:55
It didn't worked :(
I am using Wayland, but I can try to do so at X11

```
[+] EMOJI COPY BUILT
gnome-extensions install emoji-copy@felipeftn.zip --force
Extension installed successfully! Now restart the Shell ('Alt'+'F2', then 'restart').
dbus-run-session -- gnome-shell --nested --wayland
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gtk.vfs.Daemon' requested by ':1.0' (uid=1000 pid=13586 comm="gnome-shell --nested --wayland")
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gtk.vfs.Daemon'
fusermount3: failed to access mountpoint /run/user/1000/gvfs: Permission denied
libmutter-Message: 09:53:23.289: Running GNOME Shell (using mutter 46.4) as a Wayland display server
libmutter-Message: 09:53:23.289: Enabling experimental feature 'scale-monitor-framebuffer'
** Message: 09:53:23.358: Obtained a high priority EGL context
** Message: 09:53:23.359: Obtained a high priority EGL context
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.a11y.Bus' requested by ':1.2' (uid=1000 pid=13586 comm="gnome-shell --nested --wayland")
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.a11y.Bus'
Policy to allow eavesdropping in /usr/share/defaults/at-spi2/accessibility.conf +15: Eavesdropping is deprecated and ignored
Policy to allow eavesdropping in /usr/share/defaults/at-spi2/accessibility.conf +17: Eavesdropping is deprecated and ignored
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.freedesktop.systemd1' requested by ':1.4' (uid=1000 pid=13629 comm="/usr/bin/dbus-broker-launch --config-file=/usr/sha")
dbus-daemon[13585]: [session uid=1000 pid=13585] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
libmutter-Message: 09:53:23.376: Using public X11 display :2, (using :3 for managed services)

(gnome-shell:13586): libmutter-WARNING **: 09:53:23.376: WL: unable to lock lockfile /run/user/1000/wayland-0.lock, maybe another compositor is running

libmutter-Message: 09:53:23.376: Using Wayland display name 'wayland-1'
Window manager warning: Failed to set environment variable GNOME_SETUP_DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable XAUTHORITY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
Window manager warning: Failed to set environment variable WAYLAND_DISPLAY for gnome-session: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.SessionManager" does not exist
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.freedesktop.systemd1' requested by ':1.4' (uid=1000 pid=13629 comm="/usr/bin/dbus-broker-launch --config-file=/usr/sha")
dbus-daemon[13585]: [session uid=1000 pid=13585] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1

** (gnome-shell:13586): WARNING **: 09:53:23.401: AT-SPI: Could not obtain desktop path or name

dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.freedesktop.systemd1' requested by ':1.4' (uid=1000 pid=13629 comm="/usr/bin/dbus-broker-launch --config-file=/usr/sha")
dbus-daemon[13585]: [session uid=1000 pid=13585] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
GNOME Shell-Message: 09:53:23.527: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
GNOME Shell-Message: 09:53:23.528: Will monitor session 7
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gnome.Shell.Screencast' requested by ':1.0' (uid=1000 pid=13586 comm="gnome-shell --nested --wayland")
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.freedesktop.impl.portal.PermissionStore' requested by ':1.0' (uid=1000 pid=13586 comm="gnome-shell --nested --wayland")
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gnome.Shell.CalendarServer' requested by ':1.0' (uid=1000 pid=13586 comm="gnome-shell --nested --wayland")
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.freedesktop.impl.portal.PermissionStore'
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gnome.evolution.dataserver.Sources5' requested by ':1.7' (uid=1000 pid=13657 comm="/usr/lib/gnome-shell-calendar-server")
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='ca.desrt.dconf' requested by ':1.0' (uid=1000 pid=13586 comm="gnome-shell --nested --wayland")
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'ca.desrt.dconf'
GNOME Shell-Message: 09:53:23.577: Failed to create file /run/user/1000/gnome-shell-disable-extensions: Error opening file “/run/user/1000/gnome-shell-disable-extensions”: File exists
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gnome.Shell.Notifications' requested by ':1.0' (uid=1000 pid=13586 comm="gnome-shell --nested --wayland")

(gnome-shell:13586): GNOME Shell-CRITICAL **: 09:53:23.579: Could not load extension Emoji-Copy: Error: Missing metadata.json

Stack trace:
  createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:384:19
  _loadExtensions/extensionObjects<@resource:///org/gnome/shell/ui/extensionSystem.js:771:34
  _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:755:49
  async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:792:48
  _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:827:20
  async*init@resource:///org/gnome/shell/ui/extensionSystem.js:76:14
  _initializeUI@resource:///org/gnome/shell/ui/main.js:303:22
  start@resource:///org/gnome/shell/ui/main.js:175:11
  @resource:///org/gnome/shell/ui/init.js:12:47
  @resource:///org/gnome/shell/ui/init.js:21:20
  
GNOME Shell-Message: 09:53:23.580: Extension user-theme@gnome-shell-extensions.gcampax.github.com already installed in /home/jsd/.local/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com will not be loaded
GNOME Shell-Message: 09:53:23.588: Failed to launch ibus-daemon: Failed to execute child process “ibus-daemon” (No such file or directory)

** (gnome-shell:13586): WARNING **: 09:53:23.589: atk-bridge: GetRegisteredEvents returned message with unknown signature
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gnome.Shell.Notifications'

** (gnome-shell:13586): WARNING **: 09:53:23.611: atk-bridge: get_device_events_reply: unknown signature
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gnome.Shell.Screencast'
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gnome.OnlineAccounts' requested by ':1.9' (uid=1000 pid=13670 comm="/usr/lib/evolution-source-registry")
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gtk.vfs.UDisks2VolumeMonitor' requested by ':1.0' (uid=1000 pid=13586 comm="gnome-shell --nested --wayland")
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gtk.vfs.UDisks2VolumeMonitor'
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gtk.vfs.Metadata' requested by ':1.9' (uid=1000 pid=13670 comm="/usr/lib/evolution-source-registry")
goa-daemon-Message: 09:53:23.633: goa-daemon version 3.50.4 starting
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gtk.vfs.MTPVolumeMonitor' requested by ':1.0' (uid=1000 pid=13586 comm="gnome-shell --nested --wayland")
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gtk.vfs.Metadata'
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gnome.Identity' requested by ':1.12' (uid=1000 pid=13707 comm="/usr/lib/goa-daemon")
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gnome.evolution.dataserver.Sources5'
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gnome.OnlineAccounts'
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gnome.Identity'
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gtk.vfs.MTPVolumeMonitor'
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gtk.vfs.GPhoto2VolumeMonitor' requested by ':1.0' (uid=1000 pid=13586 comm="gnome-shell --nested --wayland")
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.freedesktop.secrets' requested by ':1.9' (uid=1000 pid=13670 comm="/usr/lib/evolution-source-registry")
discover_other_daemon: 1GNOME_KEYRING_CONTROL=/run/user/1000/keyring
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gtk.vfs.GPhoto2VolumeMonitor'
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gnome.evolution.dataserver.Calendar8' requested by ':1.7' (uid=1000 pid=13657 comm="/usr/lib/gnome-shell-calendar-server")
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gnome.Shell.CalendarServer'
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gtk.vfs.GoaVolumeMonitor' requested by ':1.0' (uid=1000 pid=13586 comm="gnome-shell --nested --wayland")
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gtk.vfs.GoaVolumeMonitor'
GNOME Shell-Message: 09:53:23.658: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gnome.evolution.dataserver.Calendar8'
GNOME Shell-Message: 09:53:23.694: Failed to register AuthenticationAgent
dbus-daemon[13585]: [session uid=1000 pid=13585] Activating service name='org.gnome.evolution.dataserver.AddressBook10' requested by ':1.19' (uid=1000 pid=13764 comm="/usr/lib/evolution-calendar-factory")
dbus-daemon[13585]: [session uid=1000 pid=13585] Successfully activated service 'org.gnome.evolution.dataserver.AddressBook10'

(gnome-shell:13586): GLib-GIO-CRITICAL **: 09:53:23.728: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(gnome-shell:13586): GLib-GIO-CRITICAL **: 09:53:23.733: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(gnome-shell:13586): GNOME Shell-CRITICAL **: 09:53:23.805: GLib.SpawnError: Failed to execute child process “flatpak” (No such file or directory)
updateFlatpakTheming@file:///home/jsd/.local/share/gnome-shell/extensions/custom-accent-colors@demiskp/extension.js:155:22
applyAccentColor@file:///home/jsd/.local/share/gnome-shell/extensions/custom-accent-colors@demiskp/extension.js:126:18
enable@file:///home/jsd/.local/share/gnome-shell/extensions/custom-accent-colors@demiskp/extension.js:50:14
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:266:38
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:478:32
async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:786:24
async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:792:48
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:827:20
async*init@resource:///org/gnome/shell/ui/extensionSystem.js:76:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:303:22
start@resource:///org/gnome/shell/ui/main.js:175:11
@resource:///org/gnome/shell/ui/init.js:12:47
@resource:///org/gnome/shell/ui/init.js:21:20
  
GNOME Shell-Message: 09:53:23.841: loading user theme: /home/jsd/.local/share/themes/Custom-Accent-Colors/gnome-shell/gnome-shell.css

(gnome-shell:13586): libmutter-WARNING **: 09:53:23.906: (../mutter/src/backends/meta-barrier.c:258):init_barrier_impl: runtime check failed: (priv->impl)

(gnome-shell:13586): libmutter-WARNING **: 09:53:24.082: (../mutter/src/backends/meta-barrier.c:258):init_barrier_impl: runtime check failed: (priv->impl)
GNOME Shell-Message: 09:53:24.392: GNOME Shell started at Tue Aug 20 2024 09:53:23 GMT+0200 (Central European Summer Time)
GNOME Shell-Message: 09:53:24.392: Registering session with GDM
```

**Comment by noirbizarre** [comment] 2024-08-29 12:32
I have the exact same issue. Extension was installed from EGS, no modification (v.23 currently). I run on Archlinux too (so maybe there's a pattern here)
I can reproduce it with the exact same word than in the description above.
What's weird is that some words are bringing results (`santa` like in the description above, but also `thumb`)

**Comment by oktayacikalin** [comment] 2024-09-19 09:58
Fedora Workstation 40, Gnome 46, same problem.

How can we resolve this issue?

**Comment by FelipeFTN** [comment] 2024-09-19 12:50
**@jasursadikov Pretty interesting! Thanks for sending the logs!**

This is what I'm seeing from your logs: `(gnome-shell:13586): GNOME Shell-CRITICAL **: 09:53:23.579: Could not load extension Emoji-Copy: Error: Missing metadata.json`
> This **metadata.json** refers to this file: https://github.com/FelipeFTN/Emoji-Copy/blob/master/emoji-copy%40felipeftn/metadata.json

So, can you take a look at the extension's files? You should find it at this path: `~/.local/share/gnome-shell/extensions/emoji-copy@felipeftn/`
Can you check if the file `metadata.json` exists there?
> This is also valid to you guys who are having the same issue! @oktayacikalin @noirbizarre

**Comment by oktayacikalin** [comment] 2024-09-19 20:44
@FelipeFTN Yes, it's there:

```
⋊> ~ ll ~/.local/share/gnome-shell/extensions/emoji-copy@felipeftn/                         22:42:35
drwxr-xr-x@    - oktay oktay 18 Sep 13:24  data
drwxr-xr-x@    - oktay oktay 18 Sep 13:24  handlers
drwxr-xr-x@    - oktay oktay 18 Sep 13:24  icons
drwxr-xr-x@    - oktay oktay 18 Sep 13:24  libs
drwxr-xr-x@    - oktay oktay 18 Sep 13:24  locale
drwxr-xr-x@    - oktay oktay 19 Sep 11:54  schemas
.rw-r--r--@ 7,5k oktay oktay 18 Sep 13:24  emojiButton.js
.rw-r--r--@ 5,1k oktay oktay 18 Sep 13:24  emojiCategory.js
.rw-r--r--@ 3,4k oktay oktay 18 Sep 13:24  emojiOptionsBar.js
.rw-r--r--@ 4,5k oktay oktay 18 Sep 13:24  emojiSearchItem.js
.rw-r--r--@ 7,7k oktay oktay 18 Sep 13:24  extension.js
.rw-r--r--@  35k oktay oktay 18 Sep 13:24  LICENSE
.rw-------@  490 oktay oktay 18 Sep 11:25  metadata.json
.rw-r--r--@ 4,2k oktay oktay 18 Sep 13:24  prefs.js
.rw-r--r--@ 1,3k oktay oktay 18 Sep 13:24  stylesheet.css
⋊> ~ cat ~/.local/share/gnome-shell/extensions/emoji-copy@felipeftn/metadata.json           22:42:38
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Emoji copy is a versatile extension designed to simplify emoji selection and clipboard management.\n\nIt is a fork of Emoji Selector.",
  "gettext-domain": "emoji-copy",
  "name": "Emoji Copy",
  "settings-schema": "org.gnome.shell.extensions.emoji-copy",
  "shell-version": [
    "45",
    "46",
    "47"
  ],
  "url": "https://github.com/felipeftn/emoji-copy",
  "uuid": "emoji-copy@felipeftn",
  "version": 24
}⏎     
```

**Comment by oktayacikalin** [comment] 2024-09-23 08:00
The file was there. Everything looked fine.

But I just disabled emoji-copy, deleted every setting via dconf-editor and enabled it again. Et voila it works again.

I don't have my old dconf settings anymore. @noirbizarre perhaps you can take a look at your entries? Perhaps they're malformed somehow?

**Comment by noirbizarre** [comment] 2024-09-23 17:48
I confirm uninstalling and cleaning keys fixed the issue.
For the DConf keys, there is no schema but I had the following before cleanup:
- `gender` (`int`)
- `paste-on-select` (`boolean`)
- `recently-used` (array of emojis aka. `list[string]`) 
- `skin-tone` (`int`)

Given there is no schema, on reinstall there is no key until I change a setting

**Comment by noirbizarre** [comment] 2024-09-23 17:50
Oh I think I found it: as soon as I set the skin tone, search is broken again. If I remove the key, it's working again.

**Comment by FelipeFTN** [comment] 2024-09-23 18:06
Hmmmm that's interesting... I will take a time to reproduce and try some fixes here! **Nice work @noirbizarre!! :rocket:**

**Comment by wbolster** [comment] 2024-09-30 16:14
@FelipeFTN i opened #75 with a fix

**Comment by FelipeFTN** [comment] 2024-09-30 16:48
Thanks!! I will take a look!!

**Closed** 2024-09-30 19:55 UTC
Labels: :space_invader: bug, :question: question
